/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynhansu_bst_lvtn;

import Objects.*;
import BST.*;
import java.util.Date;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class CapNhatThongTin extends javax.swing.JFrame {

    /**
     * Creates new form CapNhatThongTin
     */
    Connection connection;
    public static String maNhanVien;
    private NhanVien oldNhanVien;

    public CapNhatThongTin() {
        initComponents();
        try {
            connection = DBConnector.connect();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        GenericClass.loadComboboxFromTree(MyTrees.phongTree.root, (DefaultComboBoxModel) jComboBox_phong.getModel(), Phong::getMaPhong);
        GenericClass.loadComboboxFromTree(MyTrees.chucVuTree.root, (DefaultComboBoxModel) jComboBox_chucVu.getModel(), ChucVu::getMaChucVu);
        GenericClass.centerOnScreen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_gioiTinh = new javax.swing.ButtonGroup();
        buttonGroup_loaiNguoiDung = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_chucVu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField_matKhau = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton_quanLy = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton_nhanVien = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField_heSoLuong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_maNhanVien = new javax.swing.JTextField();
        jTextField_hoTen = new javax.swing.JTextField();
        jRadioButton_nu = new javax.swing.JRadioButton();
        jRadioButton_nam = new javax.swing.JRadioButton();
        jDateChooser_ngaySinh = new com.toedter.calendar.JDateChooser();
        jTextField_soDienThoai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_diaChi = new javax.swing.JTextArea();
        jTextField_queQuan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_phong = new javax.swing.JComboBox<>();
        jButton_capNhat = new javax.swing.JButton();
        jButton_huyBo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel2.setText("Mã nhân viên:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Số điện thoại:");

        buttonGroup_loaiNguoiDung.add(jRadioButton_quanLy);
        jRadioButton_quanLy.setText("Quản lý");

        jLabel7.setText("Địa chỉ:");

        buttonGroup_loaiNguoiDung.add(jRadioButton_nhanVien);
        jRadioButton_nhanVien.setText("Nhân viên");

        jLabel8.setText("Chức vụ:");

        jTextField_heSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_heSoLuongnumbersOnly(evt);
            }
        });

        jLabel9.setText("Mật khẩu:");

        jLabel10.setText("Phòng:");

        jLabel11.setText("Loại người dùng:");

        jLabel12.setText("Hệ số lương:");

        jLabel13.setText("Giới tính:");

        jLabel14.setText("Ngày sinh:");

        jLabel15.setText("Quê quán:");

        jTextField_maNhanVien.setEditable(false);
        jTextField_maNhanVien.setEnabled(false);
        jTextField_maNhanVien.setFocusable(false);

        jTextField_hoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_hoTencharactersOnly(evt);
            }
        });

        buttonGroup_gioiTinh.add(jRadioButton_nu);
        jRadioButton_nu.setText("Nữ");

        buttonGroup_gioiTinh.add(jRadioButton_nam);
        jRadioButton_nam.setText("Nam");

        jTextField_soDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_soDienThoainumbersOnly(evt);
            }
        });

        jTextArea_diaChi.setColumns(20);
        jTextArea_diaChi.setLineWrap(true);
        jTextArea_diaChi.setRows(5);
        jTextArea_diaChi.setPreferredSize(new java.awt.Dimension(200, 84));
        jScrollPane1.setViewportView(jTextArea_diaChi);

        jTextField_queQuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_queQuancharactersOnly(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CẬP NHẬT THÔNG TIN");

        jButton_capNhat.setText("Cập nhật");
        jButton_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_capNhatActionPerformed(evt);
            }
        });

        jButton_huyBo.setText("Hủy bỏ");
        jButton_huyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_huyBoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton_nam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton_nu))
                    .addComponent(jLabel14)
                    .addComponent(jTextField_hoTen)
                    .addComponent(jDateChooser_ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_maNhanVien)
                    .addComponent(jTextField_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButton_quanLy)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton_nhanVien))
                        .addComponent(jLabel12)
                        .addComponent(jLabel10)
                        .addComponent(jLabel15)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11)
                        .addComponent(jTextField_queQuan)
                        .addComponent(jComboBox_phong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_chucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_heSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_capNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_huyBo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_maNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRadioButton_nam)
                    .addComponent(jRadioButton_nu)
                    .addComponent(jComboBox_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jDateChooser_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_quanLy)
                    .addComponent(jRadioButton_nhanVien))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_heSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_capNhat)
                            .addComponent(jButton_huyBo)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_heSoLuongnumbersOnly(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_heSoLuongnumbersOnly
        // TODO add your handling code here:
        GenericClass.numbersOnly(evt);
    }//GEN-LAST:event_jTextField_heSoLuongnumbersOnly

    private void jTextField_hoTencharactersOnly(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_hoTencharactersOnly
        // TODO add your handling code here:
        GenericClass.charactersOnly(evt);
    }//GEN-LAST:event_jTextField_hoTencharactersOnly

    private void jTextField_soDienThoainumbersOnly(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_soDienThoainumbersOnly
        // TODO add your handling code here:
        GenericClass.numbersOnly(evt);
    }//GEN-LAST:event_jTextField_soDienThoainumbersOnly

    private void jTextField_queQuancharactersOnly(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_queQuancharactersOnly
        // TODO add your handling code here:
        GenericClass.charactersOnly(evt);
    }//GEN-LAST:event_jTextField_queQuancharactersOnly

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        HoSoNhanVien hoSoNhanVien = new HoSoNhanVien();
        hoSoNhanVien.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (!GenericClass.loaiNguoiDung) {
            jTextField_hoTen.setEnabled(false);
            jComboBox_phong.setEnabled(false);
            jComboBox_chucVu.setEnabled(false);
            jTextField_heSoLuong.setEnabled(false);
            jRadioButton_quanLy.setEnabled(false);
            jRadioButton_nhanVien.setEnabled(false);
            jRadioButton_nam.setEnabled(false);
            jRadioButton_nu.setEnabled(false);
        }
        loadData();
    }//GEN-LAST:event_formWindowActivated

    private void jButton_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_capNhatActionPerformed
        // TODO add your handling code here:
        if (jTextField_hoTen.getText().isEmpty() || jTextField_queQuan.getText().isEmpty() || jTextField_heSoLuong.getText().isEmpty() || jTextField_soDienThoai.getText().isEmpty() || jTextArea_diaChi.getText().isEmpty() || jTextField_matKhau.getText().isEmpty() || jDateChooser_ngaySinh.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ dữ liệu\nVui lòng kiểm tra lại", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            String _maNhanVien = jTextField_maNhanVien.getText();
            String hoTen = jTextField_hoTen.getText();
            int gioiTinh = jRadioButton_nam.isSelected() ? 1 : 0;
            Date ngaySinh = GenericClass.getDateFromDateChooser(jDateChooser_ngaySinh);
            String diaChi = jTextArea_diaChi.getText();
            String soDienThoai = jTextField_soDienThoai.getText();
            String queQuan = jTextField_queQuan.getText();
            String maPhong = jComboBox_phong.getSelectedItem().toString();
            String maChucVu = jComboBox_chucVu.getSelectedItem().toString();
            String matKhau = jTextField_matKhau.getText();
            boolean loaiNguoiDung = jRadioButton_quanLy.isSelected() ? true : false;
            double heSoLuong = Double.parseDouble(jTextField_heSoLuong.getText());
            String gioiTinhString = gioiTinh == 1 ? "Nam" : "Nữ";
            int loaiNguoiDungBit = loaiNguoiDung ? 1 : 0;
            LocalDate ngaySinhDate = LocalDate.parse(GenericClass.dateConverter(ngaySinh));
            if (!GenericClass.checkAge(ngaySinhDate)) {
                JOptionPane.showMessageDialog(this, "Nhân viên phải > 18 tuổi\nVui lòng kiểm tra lại", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                int luaChon = JOptionPane.showConfirmDialog(
                        this,
                        "Xác nhận lưu thay đổi?",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION);

                // Kiểm tra xem người dùng đã chọn Yes hay No
                if (luaChon == JOptionPane.YES_OPTION) {
                    MyTrees.nhanVienTree.modifyData(oldNhanVien, new NhanVien(_maNhanVien, hoTen, gioiTinhString, ngaySinh, diaChi, soDienThoai, queQuan, maPhong, maChucVu, matKhau, loaiNguoiDung, heSoLuong));
                    GenericClass.modifyDB(connection, "update nhanvien set HoTen = '" + hoTen + "', GioiTinh = '" + gioiTinhString + "', NgaySinh = '" + GenericClass.dateConverter(ngaySinh) + "', DiaChi = '" + diaChi + "', SoDienThoai = '" + soDienThoai + "', QueQuan = '" + queQuan + "', MatKhau = '" + matKhau + "', LoaiNguoiDung = b'" + loaiNguoiDungBit + "', HeSoLuong = '" + heSoLuong + "' where MaNhanVien = '" + _maNhanVien + "'", this, "Cập nhật dữ liệu thành công!");
                }
            }
        }
        this.dispose();
    }//GEN-LAST:event_jButton_capNhatActionPerformed

    private void jButton_huyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_huyBoActionPerformed
        // TODO add your handling code here:
        int luaChon = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn hủy bỏ các thay đổi?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);

        if (luaChon == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton_huyBoActionPerformed

    private void loadData() {
        jTextField_maNhanVien.setText(maNhanVien);
        try {
            oldNhanVien = getNhanVien(maNhanVien);
        } catch (Exception e) {
        }
        jTextField_hoTen.setText(oldNhanVien.getHoTen());
        if (oldNhanVien.getGioiTinh().equalsIgnoreCase("Nam")) {
            jRadioButton_nam.setSelected(true);
        } else {
            jRadioButton_nu.setSelected(true);
        }
        jDateChooser_ngaySinh.setDate(oldNhanVien.getNgaySinh());
        jTextArea_diaChi.setText(oldNhanVien.getDiaChi());
        jTextField_soDienThoai.setText(oldNhanVien.getSoDienThoai());
        jTextField_queQuan.setText(oldNhanVien.getQueQuan());
        jComboBox_phong.setSelectedItem(oldNhanVien.getMaPhong());
        jComboBox_chucVu.setSelectedItem(oldNhanVien.getMaChucVu());
        jTextField_matKhau.setText(oldNhanVien.getMatKhau());
        if (oldNhanVien.isLoaiNguoiDung()) {
            jRadioButton_quanLy.setSelected(true);
        } else {
            jRadioButton_nhanVien.setSelected(true);
        }
        jTextField_heSoLuong.setText(Double.toString(oldNhanVien.getHeSoLuong()));
    }

    private NhanVien getNhanVien(String maNhanVien) throws SQLException {
        NhanVien nhanvien = null;
        ResultSet nhanVienResultSet = GenericClass.getResultSet(connection, "select * from nhanvien where MaNhanVien = '" + maNhanVien + "'");
        while (nhanVienResultSet.next()) {
            String hoTen = nhanVienResultSet.getString("HoTen");
            String gioiTinh = nhanVienResultSet.getString("GioiTinh");
            java.sql.Date ngaySinh = nhanVienResultSet.getDate("NgaySinh");
            String diaChi = nhanVienResultSet.getString("DiaChi");
            String soDienThoai = nhanVienResultSet.getString("SoDienThoai");
            String queQuan = nhanVienResultSet.getString("QueQuan");
            String maPhong = nhanVienResultSet.getString("MaPhong");
            String maChucVu = nhanVienResultSet.getString("MaChucVu");
            String matKhau = nhanVienResultSet.getString("MatKhau");
            boolean loaiNguoiDung = nhanVienResultSet.getBoolean("LoaiNguoiDung");
            double heSoLuong = nhanVienResultSet.getDouble("HeSoLuong");
            nhanvien = new NhanVien(maNhanVien, hoTen, gioiTinh, ngaySinh, diaChi, soDienThoai, queQuan, maPhong, maChucVu, matKhau, loaiNguoiDung, heSoLuong);
        }
        return nhanvien;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhatThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhatThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhatThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhatThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapNhatThongTin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_gioiTinh;
    private javax.swing.ButtonGroup buttonGroup_loaiNguoiDung;
    private javax.swing.JButton jButton_capNhat;
    private javax.swing.JButton jButton_huyBo;
    private javax.swing.JComboBox<String> jComboBox_chucVu;
    private javax.swing.JComboBox<String> jComboBox_phong;
    private com.toedter.calendar.JDateChooser jDateChooser_ngaySinh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton_nam;
    private javax.swing.JRadioButton jRadioButton_nhanVien;
    private javax.swing.JRadioButton jRadioButton_nu;
    private javax.swing.JRadioButton jRadioButton_quanLy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_diaChi;
    private javax.swing.JTextField jTextField_heSoLuong;
    private javax.swing.JTextField jTextField_hoTen;
    private javax.swing.JTextField jTextField_maNhanVien;
    private javax.swing.JTextField jTextField_matKhau;
    private javax.swing.JTextField jTextField_queQuan;
    private javax.swing.JTextField jTextField_soDienThoai;
    // End of variables declaration//GEN-END:variables
}
