/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynhansu_bst_lvtn;

import java.net.URL;
import java.sql.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author itsHuaan
 */
public class HoSoNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form HoSoNhanVien
     */
    Connection connection;
    private String hoTen;
    private String gioiTinh;
    private Date ngaySinh;
    private String diaChi;
    private String soDienThoai;
    private String queQuan;
    private String maPhong;
    private String maChucVu;
    private String matKhau;
    public static boolean loaiNguoiDung;
    private double heSoLuong;
    private URL imgLink;
    public static boolean isFromQuanLy = false;
    public static boolean isFromDangNhap = false;
    public static boolean isFromTrangChu = false;

    public HoSoNhanVien() {
        initComponents();
        try {
            connection = DBConnector.connect();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        GenericClass.centerOnScreen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel_pfp = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton_nam = new javax.swing.JRadioButton();
        jTextField_maNhanVien = new javax.swing.JTextField();
        jTextField_hoTen = new javax.swing.JTextField();
        jRadioButton_nu = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_soDienThoai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_diaChi = new javax.swing.JTextArea();
        jTextField_queQuan = new javax.swing.JTextField();
        jTextField_heSoLuong = new javax.swing.JTextField();
        jTextField_ngaySinh = new javax.swing.JTextField();
        jTextField_phong = new javax.swing.JTextField();
        jTextField_chucVu = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_capNhatThongTin = new javax.swing.JMenuItem();
        jMenuItem_thoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_bangChamCong = new javax.swing.JMenuItem();
        jMenuItem_bangLuong = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hồ sơ nhân viên");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel_pfp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin cơ bản"));

        jLabel2.setText("Mã nhân viên:");

        jLabel3.setText("Họ tên:");

        buttonGroup1.add(jRadioButton_nam);
        jRadioButton_nam.setText("Nam");
        jRadioButton_nam.setEnabled(false);
        jRadioButton_nam.setFocusable(false);

        jTextField_maNhanVien.setEditable(false);
        jTextField_maNhanVien.setFocusable(false);

        jTextField_hoTen.setEditable(false);
        jTextField_hoTen.setFocusable(false);

        buttonGroup1.add(jRadioButton_nu);
        jRadioButton_nu.setText("Nữ");
        jRadioButton_nu.setEnabled(false);
        jRadioButton_nu.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(108, 108, 108))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(144, 144, 144))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField_maNhanVien, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jRadioButton_nam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton_nu))
                        .addComponent(jTextField_hoTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_maNhanVien)
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_hoTen)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_nam)
                    .addComponent(jRadioButton_nu))
                .addGap(32, 32, 32))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chi tiết"));

        jLabel1.setText("Ngày sinh:");

        jLabel4.setText("Số điện thoại:");

        jLabel5.setText("Địa chỉ:");

        jLabel6.setText("Quê quán:");

        jLabel7.setText("Phòng:");

        jLabel8.setText("Chức vụ:");

        jLabel9.setText("Hệ số lương:");

        jTextField_soDienThoai.setEditable(false);
        jTextField_soDienThoai.setFocusable(false);

        jTextArea_diaChi.setEditable(false);
        jTextArea_diaChi.setColumns(20);
        jTextArea_diaChi.setLineWrap(true);
        jTextArea_diaChi.setRows(5);
        jTextArea_diaChi.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea_diaChi);

        jTextField_queQuan.setEditable(false);
        jTextField_queQuan.setFocusable(false);

        jTextField_heSoLuong.setEditable(false);
        jTextField_heSoLuong.setFocusable(false);

        jTextField_ngaySinh.setEditable(false);
        jTextField_ngaySinh.setFocusable(false);

        jTextField_phong.setEditable(false);
        jTextField_phong.setFocusable(false);

        jTextField_chucVu.setEditable(false);
        jTextField_chucVu.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(177, 177, 177))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(128, 128, 128))
                            .addComponent(jTextField_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField_queQuan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_phong, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_heSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_soDienThoai)
                    .addComponent(jTextField_ngaySinh))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_queQuan)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_heSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_phong, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu1.setText("Tài khoản");

        jMenuItem_capNhatThongTin.setText("Cập nhật thông tin");
        jMenuItem_capNhatThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_capNhatThongTinActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_capNhatThongTin);

        jMenuItem_thoat.setText("Thoát");
        jMenuItem_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_thoatActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_thoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Xem");

        jMenuItem_bangChamCong.setText("Bảng chấm công");
        jMenuItem_bangChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_bangChamCongActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_bangChamCong);

        jMenuItem_bangLuong.setText("Bảng lương");
        jMenuItem_bangLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_bangLuongActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_bangLuong);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_pfp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if (isFromDangNhap) {
            isFromDangNhap = false;
            DangNhap dangNhap = new DangNhap();
            dangNhap.setVisible(true);
        }
        if (isFromQuanLy) {
            isFromQuanLy = false;
            QuanLyNhanVien quanLyNhanVien = new QuanLyNhanVien();
            quanLyNhanVien.setVisible(true);
            QuanLyNhanVien.maNhanVien = null;
        }
        if (isFromTrangChu) {
            isFromTrangChu = false;
            TrangChu trangChu = new TrangChu();
            trangChu.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String _maNhanVien;
        if (isFromQuanLy) {
            _maNhanVien = QuanLyNhanVien.maNhanVien;
        } else {
            _maNhanVien = GenericClass.maNhanVien;
        }
        loadNhanVien(_maNhanVien);
        this.setTitle("Hồ sơ nhân viên " + (String) GenericClass.getParameter(GenericClass.getResultSet(connection, "select HoTen from NhanVien where MaNhanVien = '" + _maNhanVien + "'")));
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem_capNhatThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_capNhatThongTinActionPerformed
        // TODO add your handling code here:
        CapNhatThongTin capNhatThongTin = new CapNhatThongTin();
        this.setVisible(false);
        capNhatThongTin.setVisible(true);
    }//GEN-LAST:event_jMenuItem_capNhatThongTinActionPerformed

    private void jMenuItem_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_thoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem_thoatActionPerformed

    private void jMenuItem_bangChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_bangChamCongActionPerformed
        // TODO add your handling code here:
        BangChamCong bangChamCong = new BangChamCong();
        BangChamCong.maNhanVien = jTextField_maNhanVien.getText();
        this.setVisible(false);
        bangChamCong.setVisible(true);
    }//GEN-LAST:event_jMenuItem_bangChamCongActionPerformed

    private void jMenuItem_bangLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_bangLuongActionPerformed
        // TODO add your handling code here:
        BangLuong bangLuong = new BangLuong();
        BangLuong.maNhanVien = jTextField_maNhanVien.getText();
        this.setVisible(false);
        bangLuong.setVisible(true);
    }//GEN-LAST:event_jMenuItem_bangLuongActionPerformed

    public void loadNhanVien(String maNhanVien) {
        String query = "select * from nhanvien where MaNhanVien = '" + maNhanVien + "'";
        try {
            ResultSet nhanVienResultSet = GenericClass.getResultSet(connection, query);
            while (nhanVienResultSet.next()) {
                hoTen = nhanVienResultSet.getString("HoTen");
                gioiTinh = nhanVienResultSet.getString("GioiTinh");
                ngaySinh = nhanVienResultSet.getDate("NgaySinh");
                diaChi = nhanVienResultSet.getString("DiaChi");
                soDienThoai = nhanVienResultSet.getString("SoDienThoai");
                queQuan = nhanVienResultSet.getString("QueQuan");
                maPhong = nhanVienResultSet.getString("MaPhong");
                maChucVu = nhanVienResultSet.getString("MaChucVu");
                matKhau = nhanVienResultSet.getString("MatKhau");
                loaiNguoiDung = nhanVienResultSet.getBoolean("LoaiNguoiDung");
                heSoLuong = nhanVienResultSet.getDouble("HeSoLuong");
            }
        } catch (SQLException ex) {
            Logger.getLogger(HoSoNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (isFromQuanLy) {
            jTextField_maNhanVien.setText(QuanLyNhanVien.maNhanVien);
            CapNhatThongTin.maNhanVien = QuanLyNhanVien.maNhanVien;
        } else {
            jTextField_maNhanVien.setText(GenericClass.maNhanVien);
            CapNhatThongTin.maNhanVien = GenericClass.maNhanVien;
        }
        jTextField_hoTen.setText(hoTen);
        if (gioiTinh.equalsIgnoreCase("Nam")) {
            jRadioButton_nam.setSelected(true);
            imgLink = getClass().getResource("/img/male.png");
        } else {
            jRadioButton_nu.setSelected(true);
            imgLink = getClass().getResource("/img/female.png");
        }
        GenericClass.setImage(jLabel_pfp, imgLink);
        jTextField_ngaySinh.setText(ngaySinh.toString());
        jTextField_soDienThoai.setText(soDienThoai);
        jTextArea_diaChi.setText(diaChi);
        jTextField_queQuan.setText(queQuan);
        jTextField_phong.setText((String) GenericClass.getParameter(GenericClass.getResultSet(connection, "select TenPhong from Phong where MaPhong = '" + maPhong + "'")));
        jTextField_chucVu.setText((String) GenericClass.getParameter(GenericClass.getResultSet(connection, "select TenChucVu from ChucVu where MaChucVu = '" + maChucVu + "'")));
        jTextField_heSoLuong.setText(Double.toString(heSoLuong));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoSoNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoSoNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoSoNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoSoNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoSoNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_pfp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_bangChamCong;
    private javax.swing.JMenuItem jMenuItem_bangLuong;
    private javax.swing.JMenuItem jMenuItem_capNhatThongTin;
    private javax.swing.JMenuItem jMenuItem_thoat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton_nam;
    private javax.swing.JRadioButton jRadioButton_nu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_diaChi;
    private javax.swing.JTextField jTextField_chucVu;
    private javax.swing.JTextField jTextField_heSoLuong;
    private javax.swing.JTextField jTextField_hoTen;
    private javax.swing.JTextField jTextField_maNhanVien;
    private javax.swing.JTextField jTextField_ngaySinh;
    private javax.swing.JTextField jTextField_phong;
    private javax.swing.JTextField jTextField_queQuan;
    private javax.swing.JTextField jTextField_soDienThoai;
    // End of variables declaration//GEN-END:variables
}
