/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynhansu_bst_lvtn;

import BST.MyTrees;
import Objects.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SortOrder;
import javax.swing.table.*;

/**
 *
 * @author Admin
 */
public class QuanLyChucVu extends javax.swing.JFrame {

    Connection connection;
    ChucVu oldChucVu;
    TrangChu trangChu = new TrangChu();

    /**
     * Creates new form QuanLyChucVu
     */
    public QuanLyChucVu() {
        initComponents();
        try {
            connection = DBConnector.connect();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        this.setLocationRelativeTo(trangChu);
        GenericClass.centerOnScreen(this);
    }

    private void resetInput() {
        jTextField_maChucVu.setText(GenericClass.generateRandomString("CV", 10000, 99999));
        jTextField_tenChucVu.setText(null);
        jTextField_heSoPhuCap.setText(null);
        jComboBox_thaoTac.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_heSoPhuCap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_dsChucVu = new javax.swing.JTable();
        jComboBox_thaoTac = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_maChucVu = new javax.swing.JTextField();
        jTextField_tenChucVu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý chức vụ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTextField_heSoPhuCap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_heSoPhuCapKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("QUẢN LÝ CHỨC VỤ");

        jTable_dsChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chức vụ", "Tên chức vụ", "Hệ số phụ cấp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dsChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_dsChucVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_dsChucVu);
        if (jTable_dsChucVu.getColumnModel().getColumnCount() > 0) {
            jTable_dsChucVu.getColumnModel().getColumn(0).setResizable(false);
            jTable_dsChucVu.getColumnModel().getColumn(1).setResizable(false);
            jTable_dsChucVu.getColumnModel().getColumn(2).setResizable(false);
        }

        jComboBox_thaoTac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thêm", "Cập nhật ", "Xóa" }));
        jComboBox_thaoTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_thaoTacActionPerformed(evt);
            }
        });

        jLabel6.setText("Thao tác");

        jLabel1.setText("Mã chức vụ:");

        jLabel2.setText("Tên chức vụ:");

        jLabel4.setText("Hệ số phụ cấp:");

        jTextField_maChucVu.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(140, 140, 140))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(128, 128, 128))
                            .addComponent(jTextField_maChucVu)
                            .addComponent(jTextField_heSoPhuCap)
                            .addComponent(jTextField_tenChucVu)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(142, 142, 142)))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jComboBox_thaoTac, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_maChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_tenChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_heSoPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_thaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_heSoPhuCapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_heSoPhuCapKeyTyped
        // TODO add your handling code here:
        GenericClass.numbersOnly(evt);
    }//GEN-LAST:event_jTextField_heSoPhuCapKeyTyped

    private void jTable_dsChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_dsChucVuMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_dsChucVu.getSelectedRow();
        jTextField_maChucVu.setText(jTable_dsChucVu.getValueAt(selectedRow, 0).toString());
        jTextField_tenChucVu.setText(jTable_dsChucVu.getValueAt(selectedRow, 1).toString());
        jTextField_heSoPhuCap.setText(jTable_dsChucVu.getValueAt(selectedRow, 2).toString());
        oldChucVu = new ChucVu(jTextField_maChucVu.getText(), jTextField_tenChucVu.getText(), Double.parseDouble(jTextField_heSoPhuCap.getText()));
    }//GEN-LAST:event_jTable_dsChucVuMouseClicked

    private void jComboBox_thaoTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_thaoTacActionPerformed
        // TODO add your handling code here:
        String maChucVu = jTextField_maChucVu.getText();
        String tenChucVu = jTextField_tenChucVu.getText();
        double heSoPhuCap = Double.parseDouble(jTextField_heSoPhuCap.getText());
        DefaultTableModel model = (DefaultTableModel) jTable_dsChucVu.getModel();
        switch (jComboBox_thaoTac.getSelectedIndex()) {
            case 0:
                if (maChucVu.isEmpty() || tenChucVu.isEmpty() || Double.toString(heSoPhuCap).isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Chưa nhập đủ dữ liệu\nVui lòng kiểm tra lại", "Thông báo", JOptionPane.WARNING_MESSAGE);
                } else {
                    MyTrees.chucVuTree.insert(new ChucVu(maChucVu, tenChucVu, heSoPhuCap));
                    GenericClass.modifyDB(connection, "insert into chucvu values ('" + maChucVu + "', '" + tenChucVu + "', " + heSoPhuCap + ")", this, "Thêm dữ liệu thành công!");
                    model.fireTableDataChanged();
                }
                resetInput();
                break;
            case 1:
                if (maChucVu.isEmpty() || tenChucVu.isEmpty() || Double.toString(heSoPhuCap).isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Chưa nhập đủ dữ liệu\nVui lòng kiểm tra lại", "Thông báo", JOptionPane.WARNING_MESSAGE);
                } else {
                    int luaChon = JOptionPane.showConfirmDialog(
                            this,
                            "Xác nhận thay đổi?",
                            "Xác nhận",
                            JOptionPane.YES_NO_OPTION);
                    if (luaChon == JOptionPane.YES_OPTION) {
                        ChucVu newChucVu = new ChucVu(maChucVu, tenChucVu, heSoPhuCap);
                        MyTrees.chucVuTree.modifyData(oldChucVu, newChucVu);
                        GenericClass.modifyDB(connection, "update chucvu set TenChucVu = '" + tenChucVu + "', HeSoPhuCap = " + heSoPhuCap + " where MaChucVu = '" + maChucVu + "'", this, "Cập nhật dữ liệu thành công!");
                        model.fireTableDataChanged();
                    }
                }
                resetInput();
                break;
            case 2:
                if (oldChucVu == null) {
                    JOptionPane.showMessageDialog(this, "Vui lòng chọn một đối tượng để thực hiện", "Thông báo", JOptionPane.WARNING_MESSAGE);
                } else {
                    int luaChon = JOptionPane.showConfirmDialog(
                            this,
                            "Bạn có chắc chắn muốn xóa " + oldChucVu.getTenChucVu() + "?",
                            "Xác nhận",
                            JOptionPane.YES_NO_OPTION);
                    if (luaChon == JOptionPane.YES_OPTION) {
                        MyTrees.chucVuTree.delete(oldChucVu);
                        GenericClass.modifyDB(connection, "delete from chucvu where MaChucVu = '" + maChucVu + "'", this, "Xóa dữ liệu thành công!");
                        model.fireTableDataChanged();
                    }
                }
                resetInput();
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jComboBox_thaoTacActionPerformed

    private void loadData(JTable jTable) {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        GenericClass.addObjectsToTable(jTable, 1, SortOrder.ASCENDING);
        GenericClass.getTreeData(MyTrees.chucVuTree.root, model, (ChucVu) -> new Object[]{ChucVu.getMaChucVu(), ChucVu.getTenChucVu(), ChucVu.getHeSoPhuCap()});
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jTextField_maChucVu.setText(GenericClass.generateRandomString("CV", 10000, 99999));
        loadData(jTable_dsChucVu);
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        trangChu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyChucVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_thaoTac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_dsChucVu;
    private javax.swing.JTextField jTextField_heSoPhuCap;
    private javax.swing.JTextField jTextField_maChucVu;
    private javax.swing.JTextField jTextField_tenChucVu;
    // End of variables declaration//GEN-END:variables
}
