/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynhansu_bst_lvtn;

import BST.*;
import Objects.*;
import java.sql.*;
import java.time.*;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Admin
 */
public class QuanLyNhanVien extends javax.swing.JFrame {

    Connection connection;
    NhanVien oldNhanVien;
    TrangChu trangChu = new TrangChu();
    public static String maNhanVien;
    String _maNhanVien;
    String hoTen;
    int gioiTinh;
    Date ngaySinh;
    String diaChi;
    String soDienThoai;
    String queQuan;
    String maPhong;
    String maChucVu;
    String matKhau;
    boolean loaiNguoiDung;
    double heSoLuong;
    DefaultTableModel model;

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
        try {
            connection = DBConnector.connect();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        this.setLocationRelativeTo(trangChu);
        model = (DefaultTableModel) jTable_dsNhanVien.getModel();
        GenericClass.centerOnScreen(this);
    }

    private void resetInput() {
        jTextField_maNhanVien.setText(GenericClass.generateRandomString("NV", 10000, 90000));
        jTextField_hoTen.setText(null);
        jDateChooser_ngaySinh.setDate(null);
        jRadioButton_nam.setSelected(false);
        jRadioButton_nu.setSelected(false);
        jTextField_soDienThoai.setText(null);
        jTextField_queQuan.setText(null);
        jTextArea_diaChi.setText(null);
        jComboBox_phong.setSelectedIndex(0);
        jComboBox_chucVu.setSelectedIndex(0);
        jTextField_matKhau.setText(jTextField_maNhanVien.getText());
        jTextField_heSoLuong.setText(null);
        jTextField_soDienThoai.setText(null);
        jRadioButton_quanLy.setSelected(false);
        jRadioButton_nhanVien.setSelected(false);
        jComboBox_thaoTac.setSelectedIndex(0);
    }

    private NhanVien getNhanVien(String maNhanVien) throws SQLException {
        NhanVien nhanvien = null;
        ResultSet nhanVienResultSet = GenericClass.getResultSet(connection, "select * from nhanvien where MaNhanVien = '" + maNhanVien + "'");
        while (nhanVienResultSet.next()) {
            String hoTen = nhanVienResultSet.getString("HoTen");
            String gioiTinh = nhanVienResultSet.getString("GioiTinh");
            java.sql.Date ngaySinh = nhanVienResultSet.getDate("NgaySinh");
            String diaChi = nhanVienResultSet.getString("DiaChi");
            String soDienThoai = nhanVienResultSet.getString("SoDienThoai");
            String queQuan = nhanVienResultSet.getString("QueQuan");
            String maPhong = nhanVienResultSet.getString("MaPhong");
            String maChucVu = nhanVienResultSet.getString("MaChucVu");
            String matKhau = nhanVienResultSet.getString("MatKhau");
            boolean loaiNguoiDung = nhanVienResultSet.getBoolean("LoaiNguoiDung");
            double heSoLuong = nhanVienResultSet.getDouble("HeSoLuong");
            nhanvien = new NhanVien(maNhanVien, hoTen, gioiTinh, ngaySinh, diaChi, soDienThoai, queQuan, maPhong, maChucVu, matKhau, loaiNguoiDung, heSoLuong);
        }
        return nhanvien;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu_thaoTasc = new javax.swing.JPopupMenu();
        buttonGroup_gioiTinh = new javax.swing.ButtonGroup();
        buttonGroup_loaiNguoiDung = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_dsNhanVien = new javax.swing.JTable();
        jButton_timKiem = new javax.swing.JButton();
        jTextField_timKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_thaoTac = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_maNhanVien = new javax.swing.JTextField();
        jTextField_hoTen = new javax.swing.JTextField();
        jRadioButton_nu = new javax.swing.JRadioButton();
        jRadioButton_nam = new javax.swing.JRadioButton();
        jDateChooser_ngaySinh = new com.toedter.calendar.JDateChooser();
        jTextField_soDienThoai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_diaChi = new javax.swing.JTextArea();
        jTextField_queQuan = new javax.swing.JTextField();
        jComboBox_phong = new javax.swing.JComboBox<>();
        jComboBox_chucVu = new javax.swing.JComboBox<>();
        jTextField_matKhau = new javax.swing.JTextField();
        jRadioButton_quanLy = new javax.swing.JRadioButton();
        jRadioButton_nhanVien = new javax.swing.JRadioButton();
        jTextField_heSoLuong = new javax.swing.JTextField();

        jPopupMenu_thaoTasc.setLabel("Thao tác");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý nhân viên");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable_dsNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ tên", "Ngày sinh", "Giới tính", "Quê quán", "Loại người dùng", "Mật khẩu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dsNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_dsNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_dsNhanVien);
        if (jTable_dsNhanVien.getColumnModel().getColumnCount() > 0) {
            jTable_dsNhanVien.getColumnModel().getColumn(0).setResizable(false);
            jTable_dsNhanVien.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable_dsNhanVien.getColumnModel().getColumn(1).setResizable(false);
            jTable_dsNhanVien.getColumnModel().getColumn(2).setResizable(false);
            jTable_dsNhanVien.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTable_dsNhanVien.getColumnModel().getColumn(3).setResizable(false);
            jTable_dsNhanVien.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTable_dsNhanVien.getColumnModel().getColumn(4).setResizable(false);
            jTable_dsNhanVien.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTable_dsNhanVien.getColumnModel().getColumn(5).setResizable(false);
            jTable_dsNhanVien.getColumnModel().getColumn(5).setPreferredWidth(20);
            jTable_dsNhanVien.getColumnModel().getColumn(6).setResizable(false);
            jTable_dsNhanVien.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        jButton_timKiem.setText("Tìm kiếm");
        jButton_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_timKiemActionPerformed(evt);
            }
        });

        jTextField_timKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_timKiemKeyReleased(evt);
            }
        });

        jLabel1.setText("Tìm kiếm theo mã:");

        jComboBox_thaoTac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thêm", "Chi tiết", "Xóa" }));
        jComboBox_thaoTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_thaoTacActionPerformed(evt);
            }
        });

        jLabel6.setText("Thao tác");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("QUẢN LÝ NHÂN VIÊN");

        jLabel2.setText("Mã nhân viên:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Số điện thoại:");

        jLabel7.setText("Địa chỉ:");

        jLabel8.setText("Chức vụ:");

        jLabel9.setText("Mật khẩu:");

        jLabel10.setText("Phòng:");

        jLabel11.setText("Loại người dùng:");

        jLabel12.setText("Hệ số lương:");

        jLabel13.setText("Giới tính:");

        jLabel14.setText("Ngày sinh:");

        jLabel15.setText("Quê quán:");

        jTextField_maNhanVien.setEditable(false);
        jTextField_maNhanVien.setEnabled(false);
        jTextField_maNhanVien.setFocusable(false);

        jTextField_hoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                charactersOnly(evt);
            }
        });

        buttonGroup_gioiTinh.add(jRadioButton_nu);
        jRadioButton_nu.setText("Nữ");

        buttonGroup_gioiTinh.add(jRadioButton_nam);
        jRadioButton_nam.setText("Nam");

        jTextField_soDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numbersOnly(evt);
            }
        });

        jTextArea_diaChi.setColumns(20);
        jTextArea_diaChi.setLineWrap(true);
        jTextArea_diaChi.setRows(5);
        jTextArea_diaChi.setPreferredSize(new java.awt.Dimension(200, 84));
        jScrollPane1.setViewportView(jTextArea_diaChi);

        jTextField_queQuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                charactersOnly(evt);
            }
        });

        buttonGroup_loaiNguoiDung.add(jRadioButton_quanLy);
        jRadioButton_quanLy.setText("Quản lý");

        buttonGroup_loaiNguoiDung.add(jRadioButton_nhanVien);
        jRadioButton_nhanVien.setText("Nhân viên");

        jTextField_heSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numbersOnly(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton_nam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addComponent(jRadioButton_nu))
                            .addComponent(jLabel14)
                            .addComponent(jTextField_hoTen)
                            .addComponent(jDateChooser_ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextField_maNhanVien)
                            .addComponent(jTextField_soDienThoai))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_heSoLuong, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jRadioButton_quanLy)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton_nhanVien))
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_queQuan, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox_phong, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_chucVu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_matKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jComboBox_thaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_timKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_timKiem))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButton_timKiem)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_maNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jRadioButton_nam)
                                    .addComponent(jRadioButton_nu))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jRadioButton_quanLy)
                                    .addComponent(jRadioButton_nhanVien))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_heSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_thaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        trangChu.setVisible(true);
        if (HoSoNhanVien.isFromQuanLy) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        GenericClass.loadComboboxFromTree(MyTrees.phongTree.root, (DefaultComboBoxModel) jComboBox_phong.getModel(), Phong::getMaPhong);
        GenericClass.loadComboboxFromTree(MyTrees.chucVuTree.root, (DefaultComboBoxModel) jComboBox_chucVu.getModel(), ChucVu::getMaChucVu);
        jTextField_maNhanVien.setText(GenericClass.generateRandomString("NV", 10000, 90000));
        jTextField_matKhau.setText(jTextField_maNhanVien.getText());
        loadData(jTable_dsNhanVien);
    }//GEN-LAST:event_formWindowActivated


    private void jTable_dsNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_dsNhanVienMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_dsNhanVien.getSelectedRow();
        maNhanVien = jTable_dsNhanVien.getValueAt(selectedRow, 0).toString();
        try {
            oldNhanVien = getNhanVien(maNhanVien);

        } catch (Exception e) {
            e.printStackTrace();
        }
        jTextField_maNhanVien.setText(maNhanVien);
        jTextField_hoTen.setText(jTable_dsNhanVien.getValueAt(selectedRow, 1).toString());
    }//GEN-LAST:event_jTable_dsNhanVienMouseClicked

    private void modifyDB(String query) {
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.executeUpdate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra\nVui lòng thử lại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jComboBox_thaoTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_thaoTacActionPerformed
        // TODO add your handling code here:
        try {
            _maNhanVien = jTextField_maNhanVien.getText();
            hoTen = jTextField_hoTen.getText();
            gioiTinh = jRadioButton_nam.isSelected() ? 1 : 0;
            ngaySinh = GenericClass.getDateFromDateChooser(jDateChooser_ngaySinh);
            diaChi = jTextArea_diaChi.getText();
            soDienThoai = jTextField_soDienThoai.getText();
            queQuan = jTextField_queQuan.getText();
            maPhong = jComboBox_phong.getSelectedItem().toString();
            maChucVu = jComboBox_chucVu.getSelectedItem().toString();
            matKhau = jTextField_matKhau.getText();
            loaiNguoiDung = jRadioButton_quanLy.isSelected() ? true : false;
            heSoLuong = Double.parseDouble(jTextField_heSoLuong.getText());
        } catch (Exception e) {
        }
        DefaultTableModel model = (DefaultTableModel) jTable_dsNhanVien.getModel();
        switch (jComboBox_thaoTac.getSelectedIndex()) {
            case 0:
                if (hoTen.isEmpty() || (jRadioButton_nam.isSelected() == false && jRadioButton_nu.isSelected() == false) || GenericClass.dateConverter(ngaySinh).isEmpty() || diaChi.isEmpty() || soDienThoai.isEmpty() || queQuan.isEmpty() || maPhong.isEmpty() || maChucVu.isEmpty() || matKhau.isEmpty() || (jRadioButton_quanLy.isSelected() == false && jRadioButton_nhanVien.isSelected() == false) || jTextField_heSoLuong.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Chưa nhập đủ dữ liệu\nVui lòng kiểm tra lại", "Thông báo", JOptionPane.WARNING_MESSAGE);
                } else {
                    LocalDate ngaySinhDate = LocalDate.parse(GenericClass.dateConverter(ngaySinh));
                    if (!GenericClass.checkAge(ngaySinhDate)) {
                        JOptionPane.showMessageDialog(this, "Nhân viên phải > 18 tuổi\nVui lòng kiểm tra lại", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    } else {
                        String gioiTinhString = gioiTinh == 1 ? "Nam" : "Nữ";
                        int loaiNguoiDungBit = loaiNguoiDung ? 1 : 0;
                        MyTrees.nhanVienTree.insert(new NhanVien(_maNhanVien, hoTen, gioiTinhString, ngaySinh, diaChi, soDienThoai, queQuan, maPhong, maChucVu, matKhau, loaiNguoiDung, heSoLuong));
                        GenericClass.modifyDB(connection, "insert into nhanvien values ('" + _maNhanVien + "', '" + hoTen + "', '" + gioiTinhString + "', '" + GenericClass.dateConverter(ngaySinh) + "', '" + diaChi + "', '" + soDienThoai + "', '" + queQuan + "', '" + maPhong + "', '" + maChucVu + "', '" + matKhau + "', b'" + loaiNguoiDungBit + "', '" + heSoLuong + "')", this,
                                "Thêm dữ liệu thành công");
                        model.fireTableDataChanged();
                    }
                }
                resetInput();
                break;
            case 1:
                if (maNhanVien != null) {
                    HoSoNhanVien.isFromQuanLy = true;
                    BangChamCong.maNhanVien = jTextField_maNhanVien.getText();
                    HoSoNhanVien hoSoNhanVien = new HoSoNhanVien();
                    this.setVisible(false);
                    hoSoNhanVien.setVisible(true);
                }
                break;
            case 2:
                if (maNhanVien.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Vui lòng chọn một đối tượng để thực hiện", "Thông báo", JOptionPane.WARNING_MESSAGE);
                } else {
                    int luaChon = JOptionPane.showConfirmDialog(
                            this,
                            "Bạn có chắc chắn muốn xóa nhân viên " + oldNhanVien.getHoTen() + "?",
                            "Xác nhận",
                            JOptionPane.YES_NO_OPTION);

                    // Kiểm tra xem người dùng đã chọn Yes hay No
                    if (luaChon == JOptionPane.YES_OPTION) {
                        MyTrees.nhanVienTree.delete(oldNhanVien);
                        modifyDB("delete from luong where MaNhanVien = '" + maNhanVien + "'");
                        modifyDB("delete from chamcong where MaNhanVien = '" + maNhanVien + "'");
                        GenericClass.modifyDB(connection, "delete from nhanvien where MaNhanVien = '" + maNhanVien + "'", this, "Xóa dữ liệu thành công!");
                        model.fireTableDataChanged();
                    }
                }
                resetInput();
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jComboBox_thaoTacActionPerformed

    private void jButton_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_timKiemActionPerformed
        // TODO add your handling code here:
        if (jButton_timKiem.getText().equalsIgnoreCase("tìm kiếm")) {
            if (!jTextField_timKiem.getText().isEmpty()) {
                try {
                    NhanVien nhanvienSearch = MyTrees.nhanVienTree.search(getNhanVien(jTextField_timKiem.getText().toUpperCase()));
                    model.setRowCount(0);
                    model.addRow(new Object[]{nhanvienSearch.getMaNhanVien(), nhanvienSearch.getHoTen(), nhanvienSearch.getNgaySinh(), nhanvienSearch.getGioiTinh(), nhanvienSearch.getQueQuan(), nhanvienSearch.isLoaiNguoiDung(), nhanvienSearch.getMatKhau()});
                    jTextField_timKiem.setText(null);
                    jButton_timKiem.setText("Đặt lại");
                } catch (Exception e) {
                }
            }
        } else {
            if (jTextField_timKiem.getText().isEmpty()) {
                loadData(jTable_dsNhanVien);
                jButton_timKiem.setText("Tìm kiếm");
            }
        }
    }//GEN-LAST:event_jButton_timKiemActionPerformed

    private void numbersOnly(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numbersOnly
        // TODO add your handling code here:
        GenericClass.numbersOnly(evt);
    }//GEN-LAST:event_numbersOnly

    private void charactersOnly(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_charactersOnly
        // TODO add your handling code here:
        GenericClass.charactersOnly(evt);
    }//GEN-LAST:event_charactersOnly

    private void jTextField_timKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_timKiemKeyReleased
        // TODO add your handling code here:
        if (jTextField_timKiem.getText().isEmpty() && jTable_dsNhanVien.getRowCount() == 1) {
            jButton_timKiem.setText("Đặt lại");
        } else {
            jButton_timKiem.setText("Tìm kiếm");
        }
    }//GEN-LAST:event_jTextField_timKiemKeyReleased

    private void loadData(JTable jTable) {
        GenericClass.sortTableByLastName(jTable, 1, SortOrder.ASCENDING);
        GenericClass.getTreeData(MyTrees.nhanVienTree.root, model, (NhanVien) -> new Object[]{NhanVien.getMaNhanVien(), NhanVien.getHoTen(), NhanVien.getNgaySinh(), NhanVien.getGioiTinh(), NhanVien.getQueQuan(), NhanVien.isLoaiNguoiDung(), NhanVien.getMatKhau()});
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 5).toString().equalsIgnoreCase("true")) {
                model.setValueAt("Quản lý", i, 5);
            } else {
                model.setValueAt("Nhân viên", i, 5);
            }
        }
        GenericClass.encryptPassword(jTable, 6);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_gioiTinh;
    private javax.swing.ButtonGroup buttonGroup_loaiNguoiDung;
    private javax.swing.JButton jButton_timKiem;
    private javax.swing.JComboBox<String> jComboBox_chucVu;
    private javax.swing.JComboBox<String> jComboBox_phong;
    private javax.swing.JComboBox<String> jComboBox_thaoTac;
    private com.toedter.calendar.JDateChooser jDateChooser_ngaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu_thaoTasc;
    private javax.swing.JRadioButton jRadioButton_nam;
    private javax.swing.JRadioButton jRadioButton_nhanVien;
    private javax.swing.JRadioButton jRadioButton_nu;
    private javax.swing.JRadioButton jRadioButton_quanLy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_dsNhanVien;
    private javax.swing.JTextArea jTextArea_diaChi;
    private javax.swing.JTextField jTextField_heSoLuong;
    private javax.swing.JTextField jTextField_hoTen;
    private javax.swing.JTextField jTextField_maNhanVien;
    private javax.swing.JTextField jTextField_matKhau;
    private javax.swing.JTextField jTextField_queQuan;
    private javax.swing.JTextField jTextField_soDienThoai;
    private javax.swing.JTextField jTextField_timKiem;
    // End of variables declaration//GEN-END:variables
}
