/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynhansu_bst_lvtn;

import Objects.*;
import BST.*;
import java.awt.*;
import java.sql.*;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.regex.PatternSyntaxException;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;

/**
 *
 * @author itsHuaan
 */
public class QuanLyTienLuong extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyChamCong
     */
    Connection connection;
    TrangChu trangChu = new TrangChu();

    public QuanLyTienLuong() {
        initComponents();
        try {
            connection = DBConnector.connect();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        GenericClass.loadComboboxFromTree(MyTrees.phongTree.root, (DefaultComboBoxModel) jComboBox_phong.getModel(), Phong::getMaPhong);
        GenericClass.loadCombobox((DefaultComboBoxModel) jComboBox_thang.getModel(), 1, 12);
        GenericClass.loadCombobox((DefaultComboBoxModel) jComboBox_nam.getModel(), LocalDate.now().getYear() - 50, LocalDate.now().getYear());
        GenericClass.loadCombobox((DefaultComboBoxModel) jComboBox_thangLoc.getModel(), 1, 12);
        GenericClass.loadCombobox((DefaultComboBoxModel) jComboBox_namLoc.getModel(), LocalDate.now().getYear() - 50, LocalDate.now().getYear());
        GenericClass.centerOnScreen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_bangLuong = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_dsLuong = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jComboBox_nam = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_thang = new javax.swing.JComboBox<>();
        jButton_timKiem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_maNhanVien = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_phong = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_thangLoc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_namLoc = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý tiền lương");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel_bangLuong.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTable_dsLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã lương", "Mã nhân viên", "Họ tên", "Tháng", "Năm", "Lương", "Phòng", "Thuế TNCN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_dsLuong);
        if (jTable_dsLuong.getColumnModel().getColumnCount() > 0) {
            jTable_dsLuong.getColumnModel().getColumn(0).setResizable(false);
            jTable_dsLuong.getColumnModel().getColumn(1).setResizable(false);
            jTable_dsLuong.getColumnModel().getColumn(2).setResizable(false);
            jTable_dsLuong.getColumnModel().getColumn(2).setPreferredWidth(140);
            jTable_dsLuong.getColumnModel().getColumn(3).setResizable(false);
            jTable_dsLuong.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTable_dsLuong.getColumnModel().getColumn(4).setResizable(false);
            jTable_dsLuong.getColumnModel().getColumn(4).setPreferredWidth(20);
            jTable_dsLuong.getColumnModel().getColumn(5).setResizable(false);
            jTable_dsLuong.getColumnModel().getColumn(6).setMinWidth(0);
            jTable_dsLuong.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTable_dsLuong.getColumnModel().getColumn(6).setMaxWidth(0);
            jTable_dsLuong.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel_bangLuongLayout = new javax.swing.GroupLayout(jPanel_bangLuong);
        jPanel_bangLuong.setLayout(jPanel_bangLuongLayout);
        jPanel_bangLuongLayout.setHorizontalGroup(
            jPanel_bangLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bangLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_bangLuongLayout.setVerticalGroup(
            jPanel_bangLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bangLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        jLabel1.setText("Tháng:");

        jLabel2.setText("Năm:");

        jButton_timKiem.setText("Tìm kiếm");
        jButton_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_timKiemActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã nhân viên:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addComponent(jTextField_maNhanVien))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_timKiem))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_timKiem)
                    .addComponent(jTextField_maNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lọc"));

        jLabel4.setText("Chọn phòng:");

        jComboBox_phong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_phongActionPerformed(evt);
            }
        });

        jLabel5.setText("Tháng:");

        jComboBox_thangLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_thangLocActionPerformed(evt);
            }
        });

        jLabel6.setText("Năm:");

        jComboBox_namLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_namLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_phong, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_thangLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_namLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jComboBox_thangLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_namLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_bangLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jPanel_bangLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        trangChu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        loadData(jTable_dsLuong);
    }//GEN-LAST:event_formWindowActivated

    private void jComboBox_phongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_phongActionPerformed
        // TODO add your handling code here:
        if (jComboBox_thangLoc.getSelectedItem() != null && jComboBox_namLoc.getSelectedItem() != null) {
            tableFilter(jTable_dsLuong, 2, jComboBox_phong.getSelectedItem().toString(), Integer.parseInt(jComboBox_thangLoc.getSelectedItem().toString()), Integer.parseInt(jComboBox_namLoc.getSelectedItem().toString()), SortOrder.ASCENDING);
            ((TitledBorder) jPanel_bangLuong.getBorder()).setTitle("Bảng lương " + (String) GenericClass.getParameter(GenericClass.getResultSet(connection, "select TenPhong from Phong where MaPhong = '" + jComboBox_phong.getSelectedItem().toString() + "'")));
            jPanel_bangLuong.repaint();
        }
    }//GEN-LAST:event_jComboBox_phongActionPerformed

    private Luong getLuong(String maNhanVien, int thang, int nam) throws SQLException {
        Luong luongObj = null;
        ResultSet luongResultSet = GenericClass.getResultSet(connection, "select * from luong where MaNhanVien = '" + maNhanVien + "' and Thang = " + thang + " and Nam = " + nam + "");
        while (luongResultSet.next()) {
            String maLuong = luongResultSet.getString("MaLuong");
            String _maNhanVien = luongResultSet.getString("MaNhanVien");
            int _thang = luongResultSet.getInt("Thang");
            int _nam = luongResultSet.getInt("Nam");
            double luong = luongResultSet.getDouble("Luong");
            luongObj = new Luong(maLuong, _maNhanVien, _thang, _nam, luong);
        }
        return luongObj;
    }

    private void jButton_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_timKiemActionPerformed
        // TODO add your handling code here:
        try {
            Luong searchedLuong = MyTrees.luongTree.search(getLuong(jTextField_maNhanVien.getText(), Integer.parseInt(jComboBox_thang.getSelectedItem().toString()), Integer.parseInt(jComboBox_nam.getSelectedItem().toString())));
            double tax = searchedLuong.getLuong() > 10000000 ? searchedLuong.getLuong() * 0.1 : 0;
            String hoTen = (String) GenericClass.getParameter(GenericClass.getResultSet(connection, "select HoTen from NhanVien where MaNhanVien = '" + searchedLuong.getMaNhanVien() + "'"));
            String[] columnNames = {"Mã lương", "Tháng", "Năm", "Lương", "Thuế TNCN"};
            Object[][] rowData = {
                {searchedLuong.getMaLuong(), searchedLuong.getThang(), searchedLuong.getNam(), (int) searchedLuong.getLuong(), (int) tax}
            };
            DefaultTableModel model = new DefaultTableModel(rowData, columnNames);
            JTable table = new JTable(model) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            table.setRowHeight(25);
            table.setFont(new Font("Arial", Font.PLAIN, 12));
            table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            for (int i = 0; i < table.getColumnCount(); i++) {
                table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
            JScrollPane scrollPane = new JScrollPane(table);
            scrollPane.setPreferredSize(new Dimension(400, 100));
            JOptionPane.showMessageDialog(this, scrollPane, "Thông tin lương nhân viên " + hoTen, JOptionPane.PLAIN_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace(); // Handle exceptions properly in your application
        }
    }//GEN-LAST:event_jButton_timKiemActionPerformed

    private void jComboBox_thangLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_thangLocActionPerformed
        // TODO add your handling code here:
        jComboBox_phongActionPerformed(evt);
    }//GEN-LAST:event_jComboBox_thangLocActionPerformed

    private void jComboBox_namLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_namLocActionPerformed
        // TODO add your handling code here:
        jComboBox_phongActionPerformed(evt);
    }//GEN-LAST:event_jComboBox_namLocActionPerformed
    private void loadData(JTable jTable) {
        jComboBox_thangLoc.setSelectedItem(LocalDate.now().getMonthValue());
        jComboBox_namLoc.setSelectedItem(LocalDate.now().getYear());
        GenericClass.addObjectsToTable(jTable, 4, SortOrder.ASCENDING);
        GenericClass.getTreeData(MyTrees.luongTree.root, (DefaultTableModel) jTable.getModel(), (Luong) -> new Object[]{Luong.getMaLuong(), Luong.getMaNhanVien(), 0, Luong.getThang(), Luong.getNam(), (int) Luong.getLuong()});
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            String maPhong = (String) GenericClass.getParameter(GenericClass.getResultSet(connection, "select MaPhong from NhanVien where MaNhanVien = '" + model.getValueAt(i, 1).toString() + "'"));
            model.setValueAt(maPhong, i, 6);
        }
        for (int i = 0; i < model.getRowCount(); i++) {
            String hoTen = (String) GenericClass.getParameter(GenericClass.getResultSet(connection, "select Hoten from NhanVien where MaNhanVien = '" + model.getValueAt(i, 1).toString() + "'"));
            model.setValueAt(hoTen, i, 2);
        }
//        GenericClass.tableFilter(jTable_dsLuong, 2, jComboBox_phong.getSelectedItem().toString(), SortOrder.ASCENDING);
        tableFilter(jTable, 2, jComboBox_phong.getSelectedItem().toString(), Integer.parseInt(jComboBox_thangLoc.getSelectedItem().toString()), Integer.parseInt(jComboBox_namLoc.getSelectedItem().toString()), SortOrder.ASCENDING);
        GenericClass.tinhThue(jTable, 5);
    }

    public static void tableFilter(JTable jTable, int columnIndex, String regex, int thang, int nam, SortOrder sortOrder) {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable.setRowSorter(sorter);

        RowFilter<Object, Object> regexRowFilter = null;
        try {
            regexRowFilter = RowFilter.regexFilter("\\b" + regex + "\\b");
        } catch (PatternSyntaxException e) {
            // Invalid regex
            return;
        }

        RowFilter<Object, Object> thangNamRowFilter = new RowFilter<Object, Object>() {
            public boolean include(Entry<? extends Object, ? extends Object> entry) {
                int entryThang = (Integer) entry.getValue(3);
                int entryNam = (Integer) entry.getValue(4);
                return entryThang == thang && entryNam == nam;
            }
        };

        // Combine existing regex filter and thangNam filter with an AND condition
        RowFilter<Object, Object> combinedRowFilter = RowFilter.andFilter(Arrays.asList(regexRowFilter, thangNamRowFilter));

        sorter.setRowFilter(combinedRowFilter);
        sorter.setSortKeys(Arrays.asList(new RowSorter.SortKey(columnIndex, sortOrder)));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTienLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTienLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTienLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTienLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyTienLuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_timKiem;
    private javax.swing.JComboBox<String> jComboBox_nam;
    private javax.swing.JComboBox<String> jComboBox_namLoc;
    private javax.swing.JComboBox<String> jComboBox_phong;
    private javax.swing.JComboBox<String> jComboBox_thang;
    private javax.swing.JComboBox<String> jComboBox_thangLoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_bangLuong;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_dsLuong;
    private javax.swing.JTextField jTextField_maNhanVien;
    // End of variables declaration//GEN-END:variables
}
