/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynhansu_bst_lvtn;

import BST.*;
import Objects.*;
import java.math.BigDecimal;
import java.sql.*;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SortOrder;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author itsHuaan
 */
public class QuanLyChamCong extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyChamCong
     */
    TrangChu trangChu = new TrangChu();
    Connection connection;

    public QuanLyChamCong() {
        initComponents();
        try {
            connection = DBConnector.connect();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        GenericClass.loadComboboxFromTree(MyTrees.phongTree.root, (DefaultComboBoxModel) jComboBox_phong.getModel(), Phong::getMaPhong);
        GenericClass.loadCombobox((DefaultComboBoxModel) jComboBox_thang.getModel(), 1, 12);
        GenericClass.loadCombobox((DefaultComboBoxModel) jComboBox_nam.getModel(), LocalDate.now().getYear() - 50, LocalDate.now().getYear());
        GenericClass.centerOnScreen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_thang = new javax.swing.JComboBox<>();
        jComboBox_nam = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_soNgayLamViec = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_maNhanVien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_phong = new javax.swing.JComboBox<>();
        jPanel_dsNhanVien = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_dsNhanVien = new javax.swing.JTable();
        jComboBox_thaoTac = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý chấm công");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Tháng:");

        jLabel2.setText("Năm:");

        jTextField_soNgayLamViec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_soNgayLamViecKeyTyped(evt);
            }
        });

        jLabel3.setText("Mã nhân viên:");

        jLabel5.setText("Số ngày làm việc:");

        jTextField_maNhanVien.setEditable(false);
        jTextField_maNhanVien.setFocusable(false);

        jLabel6.setText("Phòng:");

        jComboBox_phong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_phongActionPerformed(evt);
            }
        });

        jPanel_dsNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jTable_dsNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ tên", "Ngày sinh", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dsNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_dsNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_dsNhanVien);
        if (jTable_dsNhanVien.getColumnModel().getColumnCount() > 0) {
            jTable_dsNhanVien.getColumnModel().getColumn(0).setResizable(false);
            jTable_dsNhanVien.getColumnModel().getColumn(1).setResizable(false);
            jTable_dsNhanVien.getColumnModel().getColumn(2).setResizable(false);
            jTable_dsNhanVien.getColumnModel().getColumn(3).setMinWidth(0);
            jTable_dsNhanVien.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTable_dsNhanVien.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel_dsNhanVienLayout = new javax.swing.GroupLayout(jPanel_dsNhanVien);
        jPanel_dsNhanVien.setLayout(jPanel_dsNhanVienLayout);
        jPanel_dsNhanVienLayout.setHorizontalGroup(
            jPanel_dsNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_dsNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel_dsNhanVienLayout.setVerticalGroup(
            jPanel_dsNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_dsNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        jComboBox_thaoTac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chấm công", "Xem chi tiết" }));
        jComboBox_thaoTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_thaoTacActionPerformed(evt);
            }
        });

        jLabel7.setText("Thao tác:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_dsNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_maNhanVien)
                            .addComponent(jComboBox_phong, 0, 180, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox_thang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_nam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_soNgayLamViec, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jComboBox_thaoTac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_dsNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBox_phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_soNgayLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_maNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_thaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetInput() {
        jComboBox_phong.setSelectedIndex(0);
        jTextField_maNhanVien.setText(null);
        jComboBox_thang.setSelectedIndex(0);
        jComboBox_nam.setSelectedIndex(0);
        jTextField_soNgayLamViec.setText(null);
        jComboBox_thaoTac.setSelectedIndex(0);
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        trangChu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        loadData(jTable_dsNhanVien);
//        GenericClass.loadComboboxFromTree(MyTrees.phongTree.root, (DefaultComboBoxModel) jComboBox_phong.getModel(), Phong::getMaPhong);
        GenericClass.tableFilter(jTable_dsNhanVien, 1, jComboBox_phong.getSelectedItem().toString(), SortOrder.ASCENDING);
    }//GEN-LAST:event_formWindowActivated

    private void jTextField_soNgayLamViecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_soNgayLamViecKeyTyped
        // TODO add your handling code here:
        GenericClass.numbersOnly(evt);
    }//GEN-LAST:event_jTextField_soNgayLamViecKeyTyped

    private double tinhLuong(double heSoLuong, int soNgayLamViec, double heSoPhuCap) {
        double tienPhat = 0.0;
        if (soNgayLamViec < 20) {
            tienPhat = (20 - soNgayLamViec) * 500;
        }
        return (heSoLuong * 1800000 + soNgayLamViec * 200000 * heSoPhuCap) - tienPhat;
    }

    private void loadData(JTable jTable) {
        jComboBox_thang.setSelectedItem(LocalDate.now().getMonthValue());
        jComboBox_nam.setSelectedItem(LocalDate.now().getYear());
        GenericClass.addObjectsToTable(jTable, 1, SortOrder.ASCENDING);
        GenericClass.getTreeData(MyTrees.nhanVienTree.root, (DefaultTableModel) jTable_dsNhanVien.getModel(), (NhanVien) -> new Object[]{NhanVien.getMaNhanVien(), NhanVien.getHoTen(), NhanVien.getNgaySinh(), NhanVien.getMaPhong()});
    }

    private void jComboBox_phongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_phongActionPerformed
        // TODO add your handling code here:
        GenericClass.tableFilter(jTable_dsNhanVien, 1, jComboBox_phong.getSelectedItem().toString(), SortOrder.ASCENDING);
        ((TitledBorder) jPanel_dsNhanVien.getBorder()).setTitle((String) GenericClass.getParameter(GenericClass.getResultSet(connection, "select TenPhong from Phong where MaPhong = '" + jComboBox_phong.getSelectedItem().toString() + "'")));
        jPanel_dsNhanVien.repaint();
    }//GEN-LAST:event_jComboBox_phongActionPerformed

    private void jTable_dsNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_dsNhanVienMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_dsNhanVien.getSelectedRow();
        jTextField_maNhanVien.setText(jTable_dsNhanVien.getValueAt(selectedRow, 0).toString());
        BangChamCong.maNhanVien = jTextField_maNhanVien.getText();
    }//GEN-LAST:event_jTable_dsNhanVienMouseClicked

    private void insertIntoLuong(String maLuong, String maNhanVien, int thang, int nam, double luong) {
        String query = "insert into Luong values('" + maLuong + "', '" + maNhanVien + "'," + thang + ", " + nam + ", " + luong + " )";
        MyTrees.luongTree.insert(new Luong(maLuong, maNhanVien, thang, nam, luong));
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.executeUpdate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra\nVui lòng thử lại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jComboBox_thaoTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_thaoTacActionPerformed
        // TODO add your handling code here:
        LocalDate currentDate = LocalDate.now();
        int currentYear = currentDate.getYear();
        int currentMonth = currentDate.getMonthValue();
        if (jComboBox_thaoTac.getSelectedIndex() == 0) {
            if (jTextField_soNgayLamViec.getText().isEmpty() || jTextField_maNhanVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Chưa nhập đủ dữ liệu\nVui lòng kiểm tra lại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                int thang = Integer.parseInt(jComboBox_thang.getSelectedItem().toString());
                int nam = Integer.parseInt(jComboBox_nam.getSelectedItem().toString());

                // Kiểm tra năm nhuận
                boolean isLeapYear = GenericClass.isLeapYear(nam);

                if ((thang == 2 && isLeapYear && Integer.parseInt(jTextField_soNgayLamViec.getText()) > 29)
                        || (thang == 2 && !isLeapYear && Integer.parseInt(jTextField_soNgayLamViec.getText()) > 28)
                        || ((thang == 4 || thang == 6 || thang == 9 || thang == 11) && Integer.parseInt(jTextField_soNgayLamViec.getText()) > 30)
                        || (Integer.parseInt(jTextField_soNgayLamViec.getText()) > 31)) {
                    JOptionPane.showMessageDialog(this, "Số ngày làm việc không hợp lệ cho tháng và năm đã chọn", "Thông báo", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (nam > currentYear || (nam == currentYear && thang > currentMonth)) {
                        JOptionPane.showMessageDialog(this, "Thời gian không được quá thời gian hiện tại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    } else {
                        String maChamCong = GenericClass.generateRandomString("CC", 10000, 90000);
                        String maNhanVien = jTextField_maNhanVien.getText();
                        int soNgayLamViec = Integer.parseInt(jTextField_soNgayLamViec.getText());
                        long duplicateCheck = (long) GenericClass.getParameter(GenericClass.getResultSet(connection, "select count(*) from ChamCong where MaNhanVien = '" + maNhanVien + "' and Thang =" + thang + " and Nam = " + nam));
                        if (duplicateCheck > 0) {
                            JOptionPane.showMessageDialog(this, "Chấm công tháng " + thang + "/" + nam + " của nhân viên " + (String) GenericClass.getParameter(GenericClass.getResultSet(connection, "select HoTen from NhanVien where MaNhanVien = '" + maNhanVien + "'")) + " đã tồn tại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            MyTrees.chamCongTree.insert(new ChamCong(maChamCong, maNhanVien, thang, nam, soNgayLamViec));
                            GenericClass.modifyDB(connection, "insert into ChamCong values('" + maChamCong + "', '" + maNhanVien + "'," + thang + " ," + nam + " ," + soNgayLamViec + ")", this, "Thêm dữ liệu thành công!");

                            BigDecimal heSoPhuCap = (BigDecimal) GenericClass.getParameter(GenericClass.getResultSet(connection, "select cv.HeSoPhuCap from NhanVien nv join ChucVu cv on nv.MaChucVu = cv.MaChucVu where nv.MaNhanVien = '" + maNhanVien + "'"));
                            BigDecimal heSoLuong = (BigDecimal) GenericClass.getParameter(GenericClass.getResultSet(connection, "select HeSoLuong from NhanVien where MaNhanVien = '" + maNhanVien + "'"));
                            insertIntoLuong(GenericClass.generateRandomString("L", 10000, 90000), maNhanVien, thang, nam, tinhLuong(heSoLuong.doubleValue(), soNgayLamViec, heSoPhuCap.doubleValue()));
                        }
                    }
                }
                resetInput();
            }
        } else {
            GenericClass.isQuanLy = true;
            BangChamCong bangChamCong = new BangChamCong();
            BangChamCong.maNhanVien = jTextField_maNhanVien.getText();
            this.setVisible(false);
            bangChamCong.setVisible(true);
            resetInput();
        }
    }//GEN-LAST:event_jComboBox_thaoTacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyChamCong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_nam;
    private javax.swing.JComboBox<String> jComboBox_phong;
    private javax.swing.JComboBox<String> jComboBox_thang;
    private javax.swing.JComboBox<String> jComboBox_thaoTac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel_dsNhanVien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_dsNhanVien;
    private javax.swing.JTextField jTextField_maNhanVien;
    private javax.swing.JTextField jTextField_soNgayLamViec;
    // End of variables declaration//GEN-END:variables
}
