/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynhansu_bst_lvtn;

import BST.*;
import Objects.*;
import javax.swing.*;
import javax.swing.JTable;
import javax.swing.table.*;
import java.sql.*;

/**
 *
 * @author itsHuaan
 */
public class QuanLyPhong extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyPhong
     */
    Connection connection;
    Phong oldPhong;
    TrangChu trangChu = new TrangChu();

    public QuanLyPhong() {
        initComponents();
        try {
            connection = DBConnector.connect();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        this.setLocationRelativeTo(trangChu);
        GenericClass.centerOnScreen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_dsPhong = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_maPhong = new javax.swing.JTextField();
        jTextField_tenPhong = new javax.swing.JTextField();
        jTextField_diaChiPhong = new javax.swing.JTextField();
        jTextField_soDienThoai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_thaoTac = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý phòng ban");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable_dsPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Tên phòng", "Địa chỉ phòng", "Số điện thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dsPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_dsPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_dsPhong);
        if (jTable_dsPhong.getColumnModel().getColumnCount() > 0) {
            jTable_dsPhong.getColumnModel().getColumn(0).setResizable(false);
            jTable_dsPhong.getColumnModel().getColumn(1).setResizable(false);
            jTable_dsPhong.getColumnModel().getColumn(2).setResizable(false);
            jTable_dsPhong.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("Mã phòng:");

        jLabel2.setText("Tên phòng:");

        jLabel3.setText("Địa chỉ phòng:");

        jLabel4.setText("Số điện thoại:");

        jTextField_maPhong.setEditable(false);

        jTextField_soDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_soDienThoaiKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("QUẢN LÝ PHÒNG BAN");

        jComboBox_thaoTac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thêm", "Cập nhật ", "Xóa" }));
        jComboBox_thaoTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_thaoTacActionPerformed(evt);
            }
        });

        jLabel6.setText("Thao tác");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jTextField_diaChiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jTextField_tenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jTextField_maPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jComboBox_thaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_maPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_tenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_diaChiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_thaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetInput() {
        jTextField_maPhong.setText(GenericClass.generateRandomString("P", 10000, 90000));
        jTextField_tenPhong.setText(null);
        jTextField_diaChiPhong.setText(null);
        jTextField_soDienThoai.setText(null);
        jComboBox_thaoTac.setSelectedIndex(0);
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jTextField_maPhong.setText(GenericClass.generateRandomString("P", 10000, 90000));
        loadData(jTable_dsPhong);
    }//GEN-LAST:event_formWindowActivated

    private void jTable_dsPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_dsPhongMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_dsPhong.getSelectedRow();
        jTextField_maPhong.setText(jTable_dsPhong.getValueAt(selectedRow, 0).toString());
        jTextField_tenPhong.setText(jTable_dsPhong.getValueAt(selectedRow, 1).toString());
        jTextField_diaChiPhong.setText(jTable_dsPhong.getValueAt(selectedRow, 2).toString());
        jTextField_soDienThoai.setText(jTable_dsPhong.getValueAt(selectedRow, 3).toString());
        oldPhong = new Phong(jTextField_maPhong.getText(), jTextField_tenPhong.getText(), jTextField_diaChiPhong.getText(), jTextField_soDienThoai.getText());
    }//GEN-LAST:event_jTable_dsPhongMouseClicked

    private void jComboBox_thaoTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_thaoTacActionPerformed
        // TODO add your handling code here:
        String maPhong = jTextField_maPhong.getText();
        String tenPhong = jTextField_tenPhong.getText();
        String diaChiPhong = jTextField_diaChiPhong.getText();
        String soDienThoai = jTextField_soDienThoai.getText();
        DefaultTableModel model = (DefaultTableModel) jTable_dsPhong.getModel();
        switch (jComboBox_thaoTac.getSelectedIndex()) {
            case 0:
                if (maPhong.isEmpty() || tenPhong.isEmpty() || diaChiPhong.isEmpty() || soDienThoai.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Chưa nhập đủ dữ liệu\nVui lòng kiểm tra lại", "Thông báo", JOptionPane.WARNING_MESSAGE);
                } else {
                    MyTrees.phongTree.insert(new Phong(maPhong, tenPhong, diaChiPhong, soDienThoai));
                    GenericClass.modifyDB(connection, "insert into phong values ('" + maPhong + "', '" + tenPhong + "', '" + diaChiPhong + "', '" + soDienThoai + "')", this, "Thêm dữ liệu thành công!");
                    model.fireTableDataChanged();
                }
                resetInput();
                break;
            case 1:
                if (maPhong.isEmpty() || tenPhong.isEmpty() || diaChiPhong.isEmpty() || soDienThoai.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Chưa nhập đủ dữ liệu\nVui lòng kiểm tra lại", "Thông báo", JOptionPane.WARNING_MESSAGE);
                } else {
                    int luaChon = JOptionPane.showConfirmDialog(
                            this,
                            "Xác nhận thay đổi?",
                            "Xác nhận",
                            JOptionPane.YES_NO_OPTION);
                    if (luaChon == JOptionPane.YES_OPTION) {
                        MyTrees.phongTree.modifyData(oldPhong, new Phong(maPhong, tenPhong, diaChiPhong, soDienThoai));
                        GenericClass.modifyDB(connection, "update phong set TenPhong = '" + tenPhong + "', DiaChiPhong = '" + diaChiPhong + "', SoDienThoai = '" + soDienThoai + "' where MaPhong = '" + maPhong + "'", this, "Cập nhật dữ liệu thành công!");
                        model.fireTableDataChanged();
                    }
                }
                resetInput();
                break;
            case 2:
                if (maPhong.isEmpty() || tenPhong.isEmpty() || diaChiPhong.isEmpty() || soDienThoai.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Vui lòng chọn một đối tượng để thực hiện", "Thông báo", JOptionPane.WARNING_MESSAGE);
                } else {
                    int luaChon = JOptionPane.showConfirmDialog(
                            this,
                            "Bạn có chắc chắn muốn xóa " + oldPhong.getTenPhong() + "?",
                            "Xác nhận",
                            JOptionPane.YES_NO_OPTION);
                    if (luaChon == JOptionPane.YES_OPTION) {
                        MyTrees.phongTree.delete(oldPhong);
                        GenericClass.modifyDB(connection, "delete from phong where MaPhong = '" + maPhong + "'", this, "Xóa dữ liệu thành công!");
                        model.fireTableDataChanged();
                    }
                }
                resetInput();
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jComboBox_thaoTacActionPerformed

    private void jTextField_soDienThoaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_soDienThoaiKeyTyped
        // TODO add your handling code here:
        GenericClass.numbersOnly(evt);
    }//GEN-LAST:event_jTextField_soDienThoaiKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        trangChu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void loadData(JTable jTable) {
        GenericClass.addObjectsToTable(jTable, 1, SortOrder.ASCENDING);
        GenericClass.getTreeData(MyTrees.phongTree.root, (DefaultTableModel) jTable.getModel(), (Phong) -> new Object[]{Phong.getMaPhong(), Phong.getTenPhong(), Phong.getDiaChiPhong(), Phong.getSoDienThoai()});
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_thaoTac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_dsPhong;
    private javax.swing.JTextField jTextField_diaChiPhong;
    private javax.swing.JTextField jTextField_maPhong;
    private javax.swing.JTextField jTextField_soDienThoai;
    private javax.swing.JTextField jTextField_tenPhong;
    // End of variables declaration//GEN-END:variables
}
