/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynhansu_bst_lvtn;

import BST.*;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author itsHuaan
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    private static DangNhap dangNhap = null;

    public TrangChu() {
        initComponents();
        GenericClass.centerOnScreen(this);
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/logout.png"));
        Image scaledImage = icon.getImage().getScaledInstance(jButton_thoat.getWidth(), jButton_thoat.getHeight(), Image.SCALE_SMOOTH);
        jButton_thoat.setIcon(new ImageIcon(scaledImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton_quanLyNhanVien = new javax.swing.JButton();
        jButton_quanLyPhong = new javax.swing.JButton();
        jButton_thoat = new javax.swing.JButton();
        jButton_baoCaoThongKe = new javax.swing.JButton();
        jButton_quanLyChucVu = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton_quanLyChamCong = new javax.swing.JButton();
        jButton_quanLyTienLuong = new javax.swing.JButton();
        jButton_hoSoNhanVien = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel_nhanVien = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_phongBan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_chucVu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trang chủ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                TrangChu.this.windowClosed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jButton_quanLyNhanVien.setBackground(new java.awt.Color(102, 102, 102));
        jButton_quanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_quanLyNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jButton_quanLyNhanVien.setText("   Quản lý nhân viên");
        jButton_quanLyNhanVien.setBorder(null);
        jButton_quanLyNhanVien.setFocusPainted(false);
        jButton_quanLyNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_quanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quanLyNhanVienActionPerformed(evt);
            }
        });

        jButton_quanLyPhong.setBackground(new java.awt.Color(102, 102, 102));
        jButton_quanLyPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_quanLyPhong.setForeground(new java.awt.Color(255, 255, 255));
        jButton_quanLyPhong.setText("   Quản lý phòng ban");
        jButton_quanLyPhong.setBorder(null);
        jButton_quanLyPhong.setFocusPainted(false);
        jButton_quanLyPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_quanLyPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quanLyPhongActionPerformed(evt);
            }
        });

        jButton_thoat.setBackground(new java.awt.Color(102, 102, 102));
        jButton_thoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_thoat.setForeground(new java.awt.Color(255, 255, 255));
        jButton_thoat.setBorder(null);
        jButton_thoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_thoatActionPerformed(evt);
            }
        });

        jButton_baoCaoThongKe.setBackground(new java.awt.Color(102, 102, 102));
        jButton_baoCaoThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_baoCaoThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jButton_baoCaoThongKe.setText("   Báo cáo thống kê");
        jButton_baoCaoThongKe.setBorder(null);
        jButton_baoCaoThongKe.setFocusPainted(false);
        jButton_baoCaoThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_baoCaoThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_baoCaoThongKeActionPerformed(evt);
            }
        });

        jButton_quanLyChucVu.setBackground(new java.awt.Color(102, 102, 102));
        jButton_quanLyChucVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_quanLyChucVu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_quanLyChucVu.setText("   Quản lý chức vụ");
        jButton_quanLyChucVu.setBorder(null);
        jButton_quanLyChucVu.setFocusPainted(false);
        jButton_quanLyChucVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_quanLyChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quanLyChucVuActionPerformed(evt);
            }
        });

        jButton_quanLyChamCong.setBackground(new java.awt.Color(102, 102, 102));
        jButton_quanLyChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_quanLyChamCong.setForeground(new java.awt.Color(255, 255, 255));
        jButton_quanLyChamCong.setText("   Quản lý chấm công");
        jButton_quanLyChamCong.setBorder(null);
        jButton_quanLyChamCong.setFocusPainted(false);
        jButton_quanLyChamCong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_quanLyChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quanLyChamCongActionPerformed(evt);
            }
        });

        jButton_quanLyTienLuong.setBackground(new java.awt.Color(102, 102, 102));
        jButton_quanLyTienLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_quanLyTienLuong.setForeground(new java.awt.Color(255, 255, 255));
        jButton_quanLyTienLuong.setText("   Quản lý tiền lương");
        jButton_quanLyTienLuong.setBorder(null);
        jButton_quanLyTienLuong.setFocusPainted(false);
        jButton_quanLyTienLuong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_quanLyTienLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quanLyTienLuongActionPerformed(evt);
            }
        });

        jButton_hoSoNhanVien.setBackground(new java.awt.Color(102, 102, 102));
        jButton_hoSoNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_hoSoNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hoSoNhanVien.setText("Xin chào");
        jButton_hoSoNhanVien.setBorder(null);
        jButton_hoSoNhanVien.setFocusPainted(false);
        jButton_hoSoNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_hoSoNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hoSoNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_quanLyPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
            .addComponent(jButton_quanLyChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_quanLyNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_quanLyChamCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_quanLyTienLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_baoCaoThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jButton_hoSoNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton_thoat, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton_hoSoNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_quanLyPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_quanLyChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_quanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_quanLyChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_quanLyTienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_baoCaoThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel_nhanVien.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel_nhanVien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_nhanVien.setText("00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel_nhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel_nhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phòng ban", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel_phongBan.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel_phongBan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_phongBan.setText("00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel_phongBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel_phongBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel_chucVu.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel_chucVu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_chucVu.setText("00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel_chucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel_chucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logOut() {
        DangNhap dangNhap = new DangNhap();
        dangNhap.setVisible(true);
        GenericClass.clearSession();
    }

    private void windowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosed
        // TODO add your handling code here:
        logOut();
    }//GEN-LAST:event_windowClosed

    private void jButton_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_thoatActionPerformed
        // TODO add your handling code here:
        int luaChon = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);

        if (luaChon == JOptionPane.YES_OPTION) {
            this.dispose();
            GenericClass.clearSession();
        }
    }//GEN-LAST:event_jButton_thoatActionPerformed

    private void jButton_quanLyPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quanLyPhongActionPerformed
        // TODO add your handling code here:
        QuanLyPhong quanLyPhong = new QuanLyPhong();
        this.setVisible(false);
        quanLyPhong.setVisible(true);
    }//GEN-LAST:event_jButton_quanLyPhongActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
//        jButton_hoSoNhanVien.setText("<html>Xin chào<br>" + GenericClass.hoTen + "</html>");
        jButton_hoSoNhanVien.setText("<html><div style='text-align: center;'>Xin chào<br>" + GenericClass.hoTen + "</div></html>");
        jLabel_nhanVien.setText(Integer.toString(MyTrees.nhanVienTree.getNumberOfNodes()));
        jLabel_phongBan.setText(Integer.toString(MyTrees.phongTree.getNumberOfNodes()));
        jLabel_chucVu.setText(Integer.toString(MyTrees.chucVuTree.getNumberOfNodes()));
    }//GEN-LAST:event_formWindowActivated

    private void jButton_quanLyChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quanLyChucVuActionPerformed
        // TODO add your handling code here:
        QuanLyChucVu quanLyChucVu = new QuanLyChucVu();
        this.setVisible(false);
        quanLyChucVu.setVisible(true);

    }//GEN-LAST:event_jButton_quanLyChucVuActionPerformed

    private void jButton_hoSoNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hoSoNhanVienActionPerformed
        // TODO add your handling code here:
        HoSoNhanVien.isFromTrangChu = true;
        HoSoNhanVien hoSoNhanVien = new HoSoNhanVien();
        this.setVisible(false);
        hoSoNhanVien.setVisible(true);
    }//GEN-LAST:event_jButton_hoSoNhanVienActionPerformed

    private void jButton_quanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quanLyNhanVienActionPerformed
        // TODO add your handling code here:
        QuanLyNhanVien quanLyNhanVien = new QuanLyNhanVien();
        this.setVisible(false);
        quanLyNhanVien.setVisible(true);
    }//GEN-LAST:event_jButton_quanLyNhanVienActionPerformed

    private void jButton_quanLyChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quanLyChamCongActionPerformed
        // TODO add your handling code here:
        QuanLyChamCong quanLyChamCong = new QuanLyChamCong();
        this.setVisible(false);
        quanLyChamCong.setVisible(true);
    }//GEN-LAST:event_jButton_quanLyChamCongActionPerformed

    private void jButton_quanLyTienLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quanLyTienLuongActionPerformed
        // TODO add your handling code here:
        QuanLyTienLuong quanLyTienLuong = new QuanLyTienLuong();
        this.setVisible(false);
        quanLyTienLuong.setVisible(true);
    }//GEN-LAST:event_jButton_quanLyTienLuongActionPerformed

    private void jButton_baoCaoThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_baoCaoThongKeActionPerformed
        // TODO add your handling code here:
        BaoCaoThongKe baoCaoThongKe = new BaoCaoThongKe();
        this.setVisible(false);
        baoCaoThongKe.setVisible(true);
    }//GEN-LAST:event_jButton_baoCaoThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_baoCaoThongKe;
    private javax.swing.JButton jButton_hoSoNhanVien;
    private javax.swing.JButton jButton_quanLyChamCong;
    private javax.swing.JButton jButton_quanLyChucVu;
    private javax.swing.JButton jButton_quanLyNhanVien;
    private javax.swing.JButton jButton_quanLyPhong;
    private javax.swing.JButton jButton_quanLyTienLuong;
    private javax.swing.JButton jButton_thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_chucVu;
    private javax.swing.JLabel jLabel_nhanVien;
    private javax.swing.JLabel jLabel_phongBan;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
